title: Artisanal Intelligence
description: A blog about tech and other trends by crankbird
author: crankbird
baseurl: "" # Leave blank for portability
url: "" # Leave blank for clean dev/prod switching
theme: minima
permalink: /posts/:title/
markdown: kramdown
plugins: []
